### ISSUE TITLE
cannot update models in EA

### ISSUE THREAD

**Issue by tomkralidis** [ISO-TC211/HMMG#26]
Using EA 13.5, when working through https://github.com/ISO-TC211/HMMG/wiki/Connecting-to-the-Harmonized-Model-Repository, I encounter an error when trying to ['Get All Latest'](https://github.com/ISO-TC211/HMMG/wiki/Connecting-to-the-Harmonized-Model-Repository#4-get-latest-version):

![unnamed](https://user-images.githubusercontent.com/910430/47746028-7f428280-dc5b-11e8-82ad-276842ef131a.png)

Choosing 'Yes' or 'No' makes no difference, and the model remains an empty shell.  Any idea what I’m doing wrong here?

**Comment by jetgeo** [comment]
Hi Tom, is this a new error, i.e. have you been able to update before?

**Comment by tomkralidis** [comment]
@jetgeo yes this is new for me.  I've been able to update in the past.

**Comment by jetgeo** [comment]
Hm, it's difficult to say what's wrong. It works for me with EA 13.0.1310 (guess I should have updated :)) Some suggested actions for identifying the error:

You can test whether you are able to perform an svn update in Windows Explorer. If not, the problem is in your connection to the SVN repository.

You can download the latest EA project with the model from https://github.com/ISO-TC211/HMMG/blob/master/EA/ISOTC211_HM.eap and test if you are able to update in that project. If so, the problem may be in your EA project.

Have you tried updating with this EA version before?

**Comment by tomkralidis** [comment]
@jetgeo thanks for the info.  I get the exact same problem when trying to connect.

Thinking more, this may indeed be the first time I am trying with EA 13.5 (new laptop/new version).

**Comment by jetgeo** [comment]
Hi, I have upgraded to EA Version 14 on a new laptop now, and it seems to work just fine. 
Are you able to run an svn update in Windows Explorer?
I suspect that you may have set the wrong path to the working copy in EA, ref this figure: https://github.com/ISO-TC211/HMMG/raw/master/WikiIllustrations/EA_Version_Control_Settings.png. 
I suggest that you check if the path where you actually have the xmi files match the path in EA.

**Comment by tomkralidis** [comment]
It turns out the problem was rooted in invalid HTTPS certificate issues that needed to be cleared / reset across many places on my laptop. Resetting these in my SVN client seemed to do the trick.

**Comment by jetgeo** [comment]
Ok, good to hear that you were able to fix it :).
